LeanCrop/leancrop/Farmer/urls.py
from django.conf.urls import url, include
from Farmer.views import farmer_list, farm_list, schedule_list

urlpatterns = [
    url(r'^$', farmer_list, name='farmer_list'),
    url(r'^farms/$', farm_list, name='farm_list'),
    url(r'^farms/schedule/$', schedule_list, name='schedule_list'),
    # url(r'^farm-detail/(?P<id>\d+)/$', farm_detail, name='farm_detail'),
    # url(r'^schedules/$', )
]

LeanCrop/leancrop/leancrop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("Farmer.urls", namespace="farmer"))
]

LeanCrop/leancrop/Farmer/models.py
from django.db import models
import datetime

# Create your models here.
LANGUAGE_CHOICE = (
            ('English','English'),
            ('Hindi','Hindi'),
            )

class FarmerData(models.Model):
    name = models.CharField(max_length=256)
    phone_number = models.CharField(max_length=12)
    language = models.CharField(max_length=20,choices=LANGUAGE_CHOICE, default='English')

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class FarmData(models.Model):
    farmer = models.ForeignKey(FarmerData, on_delete=models.CASCADE, default=1  )
    area = models.CharField(max_length=256)
    village = models.CharField(max_length=256)
    crop_grown = models.CharField(max_length=256)
    sowing_date = models.DateField(("Sowing Date"), default=datetime.date.today)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.village

QUANTITY_UNIT_CHOICE = (
            ('ton','ton'),
            ('kg','kg'),
            ('g (Solid)','g'),
            ('L (Liquid)','L'),
            ('mL (Liquid)','mL'),
            )

class ScheduleData(models.Model):
    farmer = models.ForeignKey(FarmerData, on_delete=models.CASCADE, default=1)
    farmer_farm = models.ForeignKey(FarmData, on_delete=models.CASCADE, default=1)
    days_after_sowing = models.DateField(("Days After Sowing"), default=datetime.date.today)
    fertilizer = models.CharField(max_length=256)
    quantity = models.IntegerField()
    quantity_unit = models.CharField(max_length=20,choices=QUANTITY_UNIT_CHOICE, default='ton')

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.days_after_sowing)

LeanCrop/leancrop/Farmer/views.py
from django.shortcuts import render
from .models import FarmerData, FarmData, ScheduleData
from django.shortcuts import get_object_or_404, redirect
import datetime
# Create your views here.

def farmer_list(request):
    farmers = FarmerData.objects.all().order_by('-created_date')
    return render(request, "farmer_list.html", {"farmers":farmers})

def farm_list(request):
    farms = FarmData.objects.all().order_by('-created_date')
    return render(request, "farm_list.html", {"farms":farms})

def schedule_list(request):
    schedule = ScheduleData.objects.all().order_by('-created_date')
    farms = FarmData.objects.all().order_by('-created_date')
    return render(request, "schedule_list.html", {"schedule":schedule,"farms":farms})

LeanCrop/leancrop/templates/farm_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>leancrop | Farm</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
      table {
          border-collapse: collapse;
          border-spacing: 0;
          width: 100%;
          border: 1px solid #ddd;
      }

      th, td {
          text-align: left;
          padding: 8px;
      }

      tr:nth-child(even){background-color: #f2f2f2}
    </style>
  </head>
  <body>
    <h1> <div class="container">FARMS List:</div> </h1> <br> <br>
    <div style="overflow-x:auto;">
    <table>
    <tr>
      <th>Farm id</th>
      <th>Farmer Name</th>
      <th>Farm Area</th>
      <th>Farm Village</th>
      <th>Crop Grown</th>
      <th>Sowing Date</th>
    </tr>
    {% for i in farms %}
    <tr>
      <th>{{ i.id }}</th>
      <th>{{ i.farmer }}</th>
      <th> {{ i.area }}</th>
      <th> {{ i.village }}</th>
      <th> {{ i.crop_grown }}</th>
      <th> {{ i.sowing_date }}</th>
    </tr>
    {% endfor %}
    </table>
    </div>
  </body>
</html>

LeanCrop/leancrop/templates/farmer_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>leancrop | Farmers</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
      table {
          border-collapse: collapse;
          border-spacing: 0;
          width: 100%;
          border: 1px solid #ddd;
      }

      th, td {
          text-align: left;
          padding: 8px;
      }

      tr:nth-child(even){background-color: #f2f2f2}
    </style>
  </head>
  <body>
    {# <a href="{% url 'products:product_create' %}" class='btn btn-info btn-block'>Add New Inventory (Click Here..)</a><br> #}
    <br>
    <div class="container">
      <a href="{% url 'farmer:farm_list' %}" class="btn btn-default btn-lg">View Farm's List</a>
      <a href="{% url 'farmer:schedule_list' %}" class="btn btn-default btn-lg">View Schedule List</a>
    </div>

    <h1> <div class="container">FARMERS List:</div> </h1> <br> <br>
    <div style="overflow-x:auto;">
    <table>
    <tr>
      <th>Farmer id</th>
      <th>Farmer Data</th>
      <th>Phone Number</th>
      <th>Language</th>
    </tr>
    {% for i in farmers %}
    <tr>
      <th>{{ i.id }}</th>
      <th> {{ i.name }}</th>
      <th> {{ i.phone_number }}</th>
      <th> {{ i.language }}</th>
    </tr>
    {% endfor %}
    </table>
    </div>
  </body>
</html>

LeanCrop/leancrop/templates/schedule_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>leancrop | Farm</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
      table {
          border-collapse: collapse;
          border-spacing: 0;
          width: 100%;
          border: 1px solid #ddd;
      }

      th, td {
          text-align: left;
          padding: 8px;
      }

      tr:nth-child(even){background-color: #f2f2f2}
    </style>
  </head>
  <body>
    {# <a href="{% url 'products:product_create' %}" class='btn btn-info btn-block'>Add New Inventory (Click Here..)</a><br> #}
    <h1> <div class="container">Schedule List:</div> </h1> <br> <br>
    <div style="overflow-x:auto;">
    <table>
    <tr>
      <th>Schedule id</th>
      <th>Farmer Name</th>
      <th>Farmer's FARM Name</th>
      <th>Days after sowing</th>
      <th>Fertiliser</th>
      <th>Quantity</th>
      <th>Quantity unit</th>
      <th>Schedule Due Date</th>
    </tr>
    {% for i in schedule %}
    <tr>
      <th>{{ i.id }}</th>
      <th>{{ i.farmer }}</th>
      <th>{{ i.farmer_farm }}</th>
      <th> {{ i.days_after_sowing }}</th>
      <th> {{ i.fertilizer }}</th>
      <th> {{ i.quantity }}</th>
      <th> {{ i.quantity_unit }}</th>
      <th> {{ i.days_after_sowing }} + {{ i.farmer_farm.sowing_date }} </th>
    </tr>
    {% endfor %}
    </table>
    </div>
  </body>
</html>